---

- hosts: all
  become: true
  tasks: 

  - name: install apache2 and php packages
    package: 
      name: 
        - "{{ apache_package }}" 
        - "{{ php_package }}" 
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"] and ansible_distribution_version == "22.04"

  # - name: install apache2 package
  #   dnf: 
  #     name:  
  #       - httpd
  #       - php
  #     state: latest
  #     update_cache: true 
  #   when: ansible_distribution == "Centos"