- name: install apache2 and php packages
  tags: ubuntu
  apt: 
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution in ["Ubuntu", "Debian"] and ansible_distribution_version == "22.04"
  notify: restart_apache
  
- name: cp default file for the site
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: fathmasiddique
    group: fathmasiddique
    mode: 0644

- name: install apache2 package
  tags: centos
  dnf: 
    name:  
      - httpd
      - php
    state: latest  
  when: ansible_distribution == "Centos"
  
- name: start httpd (centos)
  tags: centos
  service: 
    name:  
      - httpd
    state: started 
    enabled: yes 
  when: ansible_distribution == "Centos"
