- name: install unzip
  tags: ubuntu
  package: 
    name: 
      - unzip

- name: install terraform
  tags: ubuntu
  unarchive: 
    src: https://releases.hashicorp.com/terraform/1.6.3/terraform_1.6.3_darwin_arm64.zip
    dest: /usr/local/bin 
    remote_src: yes
    mode: 0755 
    owner: fathmasiddique
    group: fathmasiddique
       